#!/usr/bin/env python3
import sys
import struct

def parse_bmp(filename):
    with open(filename, 'rb') as f:
        header = f.read(54)
        if header[:2] != b'BM':
            print("Not a valid BMP file")
            sys.exit(1)
            
        width, height = struct.unpack('<II', header[18:26])
        bpp = struct.unpack('<H', header[28:30])[0]
        
        if bpp != 32:
            print(f"BMP must be 32-bit ARGB. Found {bpp}-bit.")
            sys.exit(1)
            
        pixel_data_offset = struct.unpack('<I', header[10:14])[0]
        f.seek(pixel_data_offset)
        
        # BMP is stored bottom-up usually, unless height is negative
        # But we'll just read it and assume standard BGRA 32-bit layout
        row_bytes = width * 4
        pixels = []
        for y in range(height):
            row = f.read(row_bytes)
            row_pixels = []
            for x in range(width):
                b = row[x*4]
                g = row[x*4+1]
                r = row[x*4+2]
                a = row[x*4+3]
                # Combine to 0xAARRGGBB
                color = (a << 24) | (r << 16) | (g << 8) | b
                row_pixels.append(color)
            pixels.append(row_pixels)
            
        # BMP stores bottom-up, reverse it
        pixels.reverse()
        
        # Flatten
        flat_pixels = [item for sublist in pixels for item in sublist]
        return width, height, flat_pixels

def generate_c_header(name, width, height, pixels):
    header = f"// Auto-generated by img2c.py\n"
    header += f"#ifndef {name.upper()}_H\n"
    header += f"#define {name.upper()}_H\n\n"
    header += f"#include <stdint.h>\n\n"
    header += f"static const int {name}_width = {width};\n"
    header += f"static const int {name}_height = {height};\n\n"
    header += f"static const uint32_t {name}_data[{len(pixels)}] = {{\n    "
    
    for i, p in enumerate(pixels):
        header += f"0x{p:08X},"
        if (i + 1) % 8 == 0:
            header += "\n    "
        else:
            header += " "
            
    header += "\n};\n\n"
    header += f"#endif // {name.upper()}_H\n"
    return header

if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Usage: python3 img2c.py <input.bmp> <output_name>")
        print("Example: python3 img2c.py wallpaper.bmp wallpaper")
        sys.exit(1)
        
    input_file = sys.argv[1]
    name = sys.argv[2]
    output_file = f"{name}.h"
    
    print(f"Converting {input_file} to {output_file}...")
    width, height, pixels = parse_bmp(input_file)
    
    c_code = generate_c_header(name, width, height, pixels)
    with open(output_file, 'w') as f:
        f.write(c_code)
    print("Done!")
